spring:
  application:
    name: course
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: "000"
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver
    user: ${MIGRATION_POSTGRES_USER:iwa}
    password: ${MIGRATION_POSTGRES_PASSWORD:demo}
